# Generated by Django 2.2 on 2019-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191214_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='signature',
            field=models.CharField(max_length=20, verbose_name='Подпись'),
        ),
    ]
